version: '3.8'
services:
  mysql:
    container_name: ehv-db
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    networks:
      - backend-net
    volumes:
      - ehv-db-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD
  initdb:
    platform: linux/x86_64
    build: .
    command: npm run mysql:init
    environment:
      - EHV_CORE_MYSQL_HOST=mysql
      - EHV_CORE_MYSQL_PORT=3306
      - EHV_CORE_MYSQL_DATABASE=ehv_api
      - EHV_CORE_MYSQL_USER=root
      - EHV_CORE_MYSQL_PASSWORD=mysql
    volumes:
      - ./migrations:/usr/app/migrations
      - ./scripts:/usr/app/scripts
    external_links:
      - ehv-db:mysql
    networks:
      - backend-net
    depends_on:
      mysql:
        condition: service_healthy
networks:
  backend-net:
      name: ehv-backend-net
volumes:
  ehv-db-volume:
