ALTER TABLE assets ADD COLUMN `ehvAssetType` VARCHAR(255) NOT NULL AFTER `contentId`;
ALTER TABLE assets ADD COLUMN `linkageFileName` VARCHAR(255) NULL DEFAULT NULL AFTER `linkageApp`;
ALTER TABLE assets ADD COLUMN `isSpace` BOOLEAN NOT NULL DEFAULT FALSE AFTER `linkageFileName`;
ALTER TABLE assets ADD COLUMN `isApproval` BOOLEAN NULL DEFAULT NULL AFTER `isSpace`;
ALTER TABLE assets ADD COLUMN `ionPercentComplete` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ionAssetId`;
ALTER TABLE assets ADD COLUMN `category` VARCHAR(255) NOT NULL AFTER `status`;
